name: data-driven-reproducible-study
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - jupyter
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - scikit-learn
      - statsmodels
      - pyjanitor
